### ISSUE TITLE
[UI]: URL text overflow in site-card.

### ISSUE THREAD

**Issue by PriyanshuPz** [priyanshuverma-dev/quine-checkcup#2]
- [x]  Fix URL text overflow in site-card.
- [x]  Fix Title text overflow in site card

**Comment by TeoRamosKees** [comment]
Hi i will like to work on this!

**Comment by PriyanshuPz** [comment]
GO ON BRO SOLVE THE ISSUE @TeoRamosKees

**Comment by PriyanshuPz** [comment]
Please vote this project on quine [Voting link here](https://quine.sh/repo/priyanshuverma-dev-quine-checkcup-786060195?utm_source=copy&utm_share_context=quests_creators)

 @TeoRamosKees .

**Comment by TeoRamosKees** [comment]
Voted!

**Comment by PriyanshuPz** [comment]
Would you like to work on second issue @TeoRamosKees

**Comment by TeoRamosKees** [comment]
> Would you like to work on second issue @TeoRamosKees 

Yes sir, i will try to fix it in a few hours if you don't mind!
